### ISSUE TITLE
Job is shown as degraded when it succeeded

### ISSUE THREAD

**Issue by martialblog** [Icinga/icinga-kubernetes-web#56]
Some jobs in the overview are shown as degraded when they succeeded

![screenshot_2024-08-01-102603](https://github.com/user-attachments/assets/e58b14a0-65bf-445b-8591-a40d910d4179)

![screenshot_2024-08-01-103046](https://github.com/user-attachments/assets/7562b5ce-994d-4495-b63f-d2a3563febb3)

Status from the API:

```yaml
status:
  completionTime: "2024-07-31T13:06:18Z"
  conditions:
  - lastProbeTime: "2024-07-31T13:06:18Z"
    lastTransitionTime: "2024-07-31T13:06:18Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2024-07-31T13:06:00Z"
  succeeded: 1
  terminating: 0
  uncountedTerminatedPods: {}
```

icinga-kubernetes-web version: `927c646`
