### ISSUE TITLE
CronJob shows health even when all its Jobs fail

### ISSUE THREAD

**Issue by martialblog** [Icinga/icinga-kubernetes-web#59]
Hi,

A CronJob shows healthy:

![screenshot_2024-08-01-110238](https://github.com/user-attachments/assets/1c543057-805e-4f80-b6b1-730dbce3a625)

Even when all its Jobs fail:

![screenshot_2024-08-01-110243](https://github.com/user-attachments/assets/73747863-960f-434a-9b9f-561f25a1ca41)

I know there is no overall status of a cronjob in the k8s API, but a monitoring system could maybe determine the status from its jobs. Or at least give a hint that something is not right.

A CronJob's jobs show up in its status

```yaml
status:
  active:
  - apiVersion: batch/v1
    kind: Job
    name: cheapwatch-28708374
    namespace: foobar
    resourceVersion: "6273"
    uid: 766e8ddd-5618-44e6-8477-bc824da27300
```

Or the `metadata.ownerReferences` in each generated Job

```yaml
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: cheapwatch
    uid: 70ce9b18-0a61-4811-abab-1dcd1f93214a
```
